<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "eventcalendar"
 *
 * Auto generated by Extension Builder 2019-03-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Event Calendar',
    'description' => 'Event calendar with VueJS output',
    'category' => 'plugin',
    'author' => 'Mikel Wohlschlegel',
    'author_email' => 'mw@con-version.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
